### ISSUE TITLE
Add possibility to use options `-C` and `-M` for `git blame`

### ISSUE THREAD

**Issue by jonasc** [frou/st3-gitblame#21]
As the [man page](https://linux.die.net/man/1/git-blame) states, `-C` is used to correctly blame lines of code that have been moved between two files.
Note that `-C` can be given up to three times.
The same way with `-M` code that has been moved inside a file can be correctly blamed.

I can see two options to do this:
Either add a configuration option to enable/disable this (e.g. an option to add additional command line parameters) or add a second blame command which always enables `-M` and `-C` (even though it's unsure how often `-C` should be given per default).

Thanks for the help.

**Comment by psykzz** [comment]
I think this is a good addition, but im not sure on where it should exist.
As you said, we have a few options:
- configuration settings
- additional keybinds
- context menus.

Unfortunately, i've not really used `-C` or `-M` when doing git blame, but would you know if having them enabled by default would lead to any issues?

**Comment by frou** [comment]
@jonasc I'm adding this feature. Would you say the following in a `.sublime-settings` file for this Git Blame package is accurate?

```js
// Possible values for "content_chasing". The later values may cause querying
// blame information to be slower.
//
// Value                          Corresponding git-blame flags
// -----                          -----------------------------
// false                          (none)
// "same_file_same_commit"        -M
// "cross_file_same_commit"       -C
// "cross_any_file"               -C -C
// "cross_any_historical_file"    -C -C -C
//
```
```json
{
  "content_chasing": false
}
```
