### ISSUE TITLE
GitLens like functionality

### ISSUE THREAD

**Issue by jbrooksuk** [frou/st3-gitblame#24]
It'd be good if st3-gitblame could act similar to [GitLens](https://gitlens.amod.io) where it shows automatically for whichever line you're on.

You could also mimic some more of their functionality to show blames for different sections of code.

**Comment by psykzz** [comment]
I've never used gitlens could you give some examples? Screenshots or link to images that explain what you mean specifically?

**Comment by pvanb** [comment]
The line the cursor is on gets a blame annotation at the end of the line (will scroll horizontally if it doesn't fit):

<img width="1113" alt="screen shot 2018-05-17 at 10 25 13 pm" src="https://user-images.githubusercontent.com/823278/40213143-ed09d0b4-5a21-11e8-98be-3be4bb3a8d8e.png">

When hovering over the blame annotation a popup with more detail is shown:

<img width="1110" alt="screen shot 2018-05-17 at 10 25 54 pm" src="https://user-images.githubusercontent.com/823278/40213181-20e41bb0-5a22-11e8-91d2-8bcc3e760fbc.png">

GitLens calls it [Current Line Blame](https://github.com/eamodio/vscode-gitlens/#current-line-blame).

**Comment by pvanb** [comment]
Here it is in action...

![may-17-2018 22-56-32](https://user-images.githubusercontent.com/823278/40214008-7c926d28-5a26-11e8-8221-1e4e8a7415ed.gif)

**Comment by jbrooksuk** [comment]
Thanks @pvanb I've not had time to do this.

**Comment by pvanb** [comment]
I played with this a little bit and I'm not so sure it's going to be possible. On non-blank lines using ``sublime.LAYOUT_INLINE`` for the Phantoms is fine, but on blank lines they get added before the cursor instead of after.

From the documentation:
> ``sublime.LAYOUT_INLINE``: Display the phantom in between the ``region`` and the point following.

On blank lines I guess there is effectively no region, so it gets added between the end of the previous line and the cursor? Here's a code snippet of what I'm trying:
```
        # get selected regions as RegionSet
        sels = view.sel()

        # get 1st cursor as Region
        region = sels[0]

        # get the current line
        line = view.line(region)

        # get row, col
        row, col = view.rowcol(point)

        anchor = sublime.Region(line.end(), line.end())
        body = template.format(line=str(row), stylesheet=stylesheet)

        phantom = sublime.Phantom(anchor, body, sublime.LAYOUT_INLINE, self.on_phantom_click)
        phantoms.append(phantom)
        self.phantom_set.update(phantoms)
```
And here's how it behaves:

![may-19-2018 16-07-28](https://user-images.githubusercontent.com/823278/40272781-5b3d19c8-5b81-11e8-86ec-da88c966de4b.gif)

**Comment by jbrooksuk** [comment]
@wbond any ideas?

**Comment by jbrooksuk** [comment]
Could you not create a region manually?

**Comment by pvanb** [comment]
My understanding of regions is that they're based on the contents of the buffer, so I don't think you can create one outside of the bounds of the content (i.e. beyond the cursor on a blank line.) In my attempts to do so (e.g. ``line.end() + 1``) the phantom ends up on the next line.

Hopefully I'm wrong and I'm missing something. Today was literally my first time writing Sublime plugins.

**Comment by psykzz** [comment]
I took a stab myself, but didn't get to fix the issue with the empty lines, instead I just opt to hide those lines
https://github.com/psykzz/st3-gitblame/pull/27 is open for review
http://g.recordit.co/Ql9zKjWMsR.gif
