### ISSUE TITLE
Author/commiter names with more than one space not being parsed correctly

### ISSUE THREAD

**Issue by pvanb** [frou/st3-gitblame#29]
As an example:
<img width="617" alt="screen shot 2018-05-23 at 10 26 30 am" src="https://user-images.githubusercontent.com/823278/40430764-d930e900-5e73-11e8-906f-8c147517de3f.png">

It should read: 
**Git Blame** (Peter van Broekhoven) 2018-05-14 | b2d8b444 [Copy] [Show] ×

Using the ``-p`` (``--porcelain``) option I think would provide the output in a more parsable format (not sure if there's a performance hit though):
```
→ git blame -L 1484,1484 -p Something.js
b2d8b44476e48061bc50e81702fc945d11b4bc53 1394 1484 1
author Peter van Broekhoven
author-mail <...>
author-time 1526327585
author-tz -0400
committer Peter van Broekhoven
committer-mail <...>
committer-time 1526327585
committer-tz -0400
summary Commit message
previous beee2e2ab39a4fce2d8104bbade7e124e80bdc0f Something.js
filename Something.js
                    /*
```

**Comment by psykzz** [comment]
This will actually get fixed if #27 is merged.

We had a better regex for showing the blame for the entire file and i refactored so we use the same regex for all blames.
