### ISSUE TITLE
Git Blame not working on Sublime Text 3 in Windows

### ISSUE THREAD

**Issue by drbartling** [frou/st3-gitblame#30]
I get the following error:
```
Git blame: git error 128:
fatal: no such path 'C:\Users\<path_to_file>\<file_name>' in HEAD
```

I'll note that other sublime plugins work (like git gutter and git)  and others do not (like SublimeGit).

It appears the main difference is the path that gets passed to the git command

**Comment by psykzz** [comment]
Thanks for the report,

Few questions,

- How incorrect is the path?
- Is it malformed like `C:\Users\C:\Users\<path_to_file>\<file_name>`

I suspect the path is wrong as you pointed out, just need to know how bad its wrong.

**Comment by drbartling** [comment]
It's using the correct absolute path.  I suspect it would work using a relative path.

**Comment by drbartling** [comment]
Git blame: git error 128:
fatal: no such path 'src/C:\Users\rybartli\Documents\git_tmp\debounced_button\src\debounced_button.h' in HEAD

**Comment by drbartling** [comment]
Is there any more information you need?

**Comment by frou** [comment]
@drbartling A new version (1.1.4) has been released on Package Control that might resolve this. Could you please try it?
