### ISSUE TITLE
Unexpected error: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by YYCoder** [frou/st3-gitblame#32]
I get this error while using Git Blame, last week it works just fine. I'm not sure what I have done to cause this situation. Using git blame on terminal works fine.

Environment：OS X 10.13.6

git status log like this:

```text
On branch f_feat_jira4492
Your branch is up to date with 'origin/f_feat_jira4492'.

nothing to commit, working tree clean
```

**Comment by frou** [comment]
Has this error still been bothering you or was it just a one-off?
