### ISSUE TITLE
Owner wanted

### ISSUE THREAD

**Issue by psykzz** [frou/st3-gitblame#35]
Hey,

As you may have noticed the number of issues with this project have been rising recently and i haven't had the time to fix any of them, another reason being that I have moved away from using Sublime text daily and haven't been keeping myself up to date.

That said, I'm looking for someone else who wants to own and/or maintain this project going forward. 

Please feel free to reach out to me here, or on twitter [@psykzz](https://twitter.com/psykzz)

**Comment by frou** [comment]
Matt - I'd be happy to do so. I anticipate being Sublime-4-Lyfe, and have made a decent number of merged PRs so far:

* #9
* #13
* #14
* #22
* #23
* #26

**Comment by psykzz** [comment]
Great @frou! How would you like to proceed?

The package is registered in the package control over at https://github.com/wbond/package_control_channel/blob/master/repository/g.json#L466-L476

If you like, I can just add you as a collaborator on this repo and you can work out the migration plan to another repo later, if you'd prefer that?

**Comment by frou** [comment]
I haven't done this before, but it sounds like these days GitHub's repository transfer feature is very smart and, among other things, creates redirects for everything:

https://help.github.com/en/articles/transferring-a-repository

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. [...]

If we use that then I will delete my existing fork beforehand.

**Comment by psykzz** [comment]
I think you'll need to update the package control repo first, otherwise you wont be able to publish updates, once you're ready though let me know ill transfer it.

**Comment by frou** [comment]
Yep, I guess this is what we want to aim for:

* No disruption to users who already have it installed.
* Minimal duration during which new users are unable to install it.
* The only issue tracker lives under `github.com/frou/st3-gitblame` and includes all historical issues.

GIven that master on my old fork diverged a bit from your repo's master, I think the following is the way to go:

1. I delete my old fork.
2. I make a fresh fork of your repo.
3. I make a PR to Package Control to change the repo URL.
4. (Time passes) and then the Package Control maintainers merge the PR.
5. You and I arrange a date and time to do the last step.
6. At that date and time, I delete my fresh fork and then you initiate the transfer.

**Comment by psykzz** [comment]
@frou Sounds great.

**Comment by frou** [comment]
That's Package Control updated. Let me know when you're around to do the last part and I'll notice on my phone. Should only take a couple of minutes if it goes smoothly!

**Comment by psykzz** [comment]
@frou i'm around all of today to do the change, let me know a time that suits you as well.

**Comment by frou** [comment]
I just deleted my fork, so you should be able to start the transfer

**Comment by psykzz** [comment]
Doing it now.

**Comment by psykzz** [comment]
Looks completed! Congrats! and thank you for taking over!

**Comment by frou** [comment]
Cheers!
