### ISSUE TITLE
When presenting commit-skipping modes in the Command Palette, preselect the one currently in effect

### ISSUE THREAD

**Issue by 0pdd** [frou/st3-gitblame#41]
The puzzle `21-a3b5cdc3` from #21 has to be resolved: 

https://github.com/frou/st3-gitblame/blob/183b169593749ebbe301ad878371d1ea7dcbeb34/commit_skipping.py#L59-L59

The puzzle was created by Duncan Holm on 30-Jun-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Not gonna release "Commit Skipping Mode" because it's overly fiddly. Will do #50 instead.
