### ISSUE TITLE
Factor out loading of the commit-skipping mode so that the BlameShowAll command can use it too.

### ISSUE THREAD

**Issue by 0pdd** [frou/st3-gitblame#46]
The puzzle `21-043a8f06` from #21 has to be resolved: 

https://github.com/frou/st3-gitblame/blob/320458e8f0e8c85343e5835cca0d80e46d41f9da/src/blame.py#L31-L31

The puzzle was created by Duncan Holm on 30-Jun-19. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Not gonna release "Commit Skipping Mode" because it's overly fiddly. Will do #50 instead.
