### ISSUE TITLE
The context menu of st3 is disable

### ISSUE THREAD

**Issue by shyhsheng** [frou/st3-gitblame#48]
Hi ,

My ST3 version is 3.2.1 Build 3207.
The context menu always disable that I can't use it.
![P_20190717_205619](https://user-images.githubusercontent.com/6959408/61377294-81c23680-a8d5-11e9-999e-cc90fe5c933f.jpg)

thanks

**Comment by frou** [comment]
Did you get it working? I was going to ask if there are any errors in the console when Sublime starts up (View > Show Console), and also if the "Git Blame" command is shown in the command palette (Tools > Command Palette)
