### ISSUE TITLE
Unavailable in  "Package Control" now?

### ISSUE THREAD

**Issue by heshiweij** [frou/st3-gitblame#71]
I can't search "Git Blame" in package control!
![image](https://user-images.githubusercontent.com/5785421/178139653-3ccc2268-db5b-41c4-9fed-7149ce35a58f.png)

**Comment by frou** [comment]
It is still available. Maybe your version of Sublime Text is too outdated (the package requires ST3 build 3170 or higher) or even you already have the package installed?

**Comment by heshiweij** [comment]
Ok, my  ST is too outdated. Thx  :)
![image](https://user-images.githubusercontent.com/5785421/178400777-aadd9b9e-c568-4a03-bb38-f527d6ef6cb4.png)
